<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NotificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table("notification")->insert([
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '4', 'reference_id' => '2', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-04 13:55:30', 'updated_at' => '2021-06-04 13:55:30', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '4', 'target_id' => '5', 'reference_id' => '3', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-04 13:56:49', 'updated_at' => '2021-06-04 13:56:49', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '3', 'target_id' => '9', 'reference_id' => '5', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-07 09:34:43', 'updated_at' => '2021-06-07 09:34:43', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '9', 'target_id' => '3', 'reference_id' => '6', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-07 09:34:45', 'updated_at' => '2021-06-07 09:34:45', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '8', 'reference_id' => '7', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-07 13:30:01', 'updated_at' => '2021-06-07 13:30:01', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '8', 'target_id' => '5', 'reference_id' => '9', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-07 13:34:44', 'updated_at' => '2021-06-07 13:34:44', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '17', 'target_id' => '5', 'reference_id' => '10', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-07 15:45:18', 'updated_at' => '2021-06-07 15:45:18', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '6', 'target_id' => '1', 'reference_id' => '11', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-08 06:33:25', 'updated_at' => '2021-06-08 06:33:25', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '6', 'reference_id' => '12', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-08 06:33:36', 'updated_at' => '2021-06-08 06:33:36', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '5', 'reference_id' => '4', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-08 06:33:39', 'updated_at' => '2021-06-08 06:33:39', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '7', 'reference_id' => '14', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-08 08:05:15', 'updated_at' => '2021-06-08 08:05:15', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '7', 'target_id' => '1', 'reference_id' => '15', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-08 08:05:20', 'updated_at' => '2021-06-08 08:05:20', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '17', 'reference_id' => '16', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-06-08 08:47:37', 'updated_at' => '2021-06-08 08:47:37', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '19', 'reference_id' => '18', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-08 11:59:25', 'updated_at' => '2021-06-08 11:59:25', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '19', 'target_id' => '5', 'reference_id' => '17', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-08 11:59:39', 'updated_at' => '2021-06-08 11:59:39', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '1', 'actor_id' => '7', 'target_id' => '19', 'reference_id' => '20', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-06-08 12:09:46', 'updated_at' => '2021-06-08 12:09:46', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '26', 'target_id' => '5', 'reference_id' => '24', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-09 20:30:52', 'updated_at' => '2021-06-09 20:30:52', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '26', 'reference_id' => '23', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-09 20:30:59', 'updated_at' => '2021-06-09 20:30:59', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '1', 'actor_id' => '7', 'target_id' => '26', 'reference_id' => '25', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-09 20:53:05', 'updated_at' => '2021-06-09 20:53:05', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '26', 'target_id' => '1', 'reference_id' => '28', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-11 09:56:50', 'updated_at' => '2021-06-11 09:56:50', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '1', 'actor_id' => '1', 'target_id' => '2', 'reference_id' => '30', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-11 11:43:10', 'updated_at' => '2021-06-11 11:43:10', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '26', 'reference_id' => '29', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-06-11 13:28:32', 'updated_at' => '2021-06-11 13:28:32', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '9', 'actor_id' => '1', 'target_id' => '1', 'reference_id' => '31', 'reference_module' => 'request_rejected', 'type' => 'push', 'title' => 'Request Rejected', 'description' => 'Request Rejected', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-14 13:19:39', 'updated_at' => '2021-06-14 13:19:39', 'custom_data' => NULL, 'status_code' => '2'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '36', 'reference_id' => '32', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-14 13:22:40', 'updated_at' => '2021-06-14 13:22:40', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '36', 'target_id' => '1', 'reference_id' => '33', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-14 13:25:30', 'updated_at' => '2021-06-14 13:25:30', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '1', 'actor_id' => '37', 'target_id' => '35', 'reference_id' => '34', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-06-14 14:02:01', 'updated_at' => '2021-06-14 14:02:01', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '37', 'target_id' => '3', 'reference_id' => '36', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-14 15:00:15', 'updated_at' => '2021-06-14 15:00:15', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '3', 'target_id' => '37', 'reference_id' => '37', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-14 15:00:20', 'updated_at' => '2021-06-14 15:00:20', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '9', 'actor_id' => '37', 'target_id' => '35', 'reference_id' => '35', 'reference_module' => 'request_rejected', 'type' => 'push', 'title' => 'Request Rejected', 'description' => 'Request Rejected', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-06-14 15:00:22', 'updated_at' => '2021-06-14 15:00:22', 'custom_data' => NULL, 'status_code' => '2'],
            ['notification_identifier_id' => '1', 'actor_id' => '22', 'target_id' => '34', 'reference_id' => '41', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-15 19:56:26', 'updated_at' => '2021-06-15 19:56:26', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '22', 'target_id' => '34', 'reference_id' => '40', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-15 19:58:03', 'updated_at' => '2021-06-15 19:58:03', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '22', 'target_id' => '1', 'reference_id' => '42', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-15 20:09:31', 'updated_at' => '2021-06-15 20:09:31', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '22', 'reference_id' => '43', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-15 20:09:36', 'updated_at' => '2021-06-15 20:09:36', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '3', 'target_id' => '1', 'reference_id' => '44', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-16 09:28:20', 'updated_at' => '2021-06-16 09:28:20', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '40', 'target_id' => '22', 'reference_id' => '45', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-16 13:55:50', 'updated_at' => '2021-06-16 13:55:50', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '1', 'actor_id' => '1', 'target_id' => '40', 'reference_id' => '47', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-16 14:07:40', 'updated_at' => '2021-06-16 14:07:40', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '22', 'target_id' => '41', 'reference_id' => '48', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-16 15:02:02', 'updated_at' => '2021-06-16 15:02:02', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '41', 'target_id' => '22', 'reference_id' => '49', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-16 15:02:02', 'updated_at' => '2021-06-16 15:02:02', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '38', 'target_id' => '43', 'reference_id' => '50', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-21 19:45:41', 'updated_at' => '2021-06-21 19:45:41', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '38', 'target_id' => '9', 'reference_id' => '39', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-21 19:45:43', 'updated_at' => '2021-06-21 19:45:43', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '9', 'target_id' => '38', 'reference_id' => '52', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-06-22 16:42:50', 'updated_at' => '2021-06-22 16:42:50', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '1', 'actor_id' => '5', 'target_id' => '22', 'reference_id' => '53', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-07-01 13:58:25', 'updated_at' => '2021-07-01 13:58:25', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '46', 'target_id' => '1', 'reference_id' => '55', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-20 10:26:38', 'updated_at' => '2021-07-20 10:26:38', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '46', 'reference_id' => '54', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-20 10:26:41', 'updated_at' => '2021-07-20 10:26:41', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '40', 'reference_id' => '46', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-07-20 13:04:08', 'updated_at' => '2021-07-20 13:04:08', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '6', 'target_id' => '46', 'reference_id' => '56', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-26 06:31:49', 'updated_at' => '2021-07-26 06:31:49', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '9', 'actor_id' => '49', 'target_id' => '5', 'reference_id' => '57', 'reference_module' => 'request_rejected', 'type' => 'push', 'title' => 'Request Rejected', 'description' => 'Request Rejected', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-28 17:29:54', 'updated_at' => '2021-07-28 17:29:54', 'custom_data' => NULL, 'status_code' => '2'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '49', 'reference_id' => '58', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-28 17:30:05', 'updated_at' => '2021-07-28 17:30:05', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '7', 'reference_id' => '38', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-28 17:30:08', 'updated_at' => '2021-07-28 17:30:08', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '1', 'reference_id' => '19', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-28 17:30:24', 'updated_at' => '2021-07-28 17:30:24', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '47', 'target_id' => '46', 'reference_id' => '59', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-28 17:42:25', 'updated_at' => '2021-07-28 17:42:25', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '2', 'reference_id' => '13', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-07-28 17:51:20', 'updated_at' => '2021-07-28 17:51:20', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '49', 'reference_id' => '60', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-28 17:51:30', 'updated_at' => '2021-07-28 17:51:30', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '49', 'target_id' => '1', 'reference_id' => '61', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-28 17:51:49', 'updated_at' => '2021-07-28 17:51:49', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '47', 'reference_id' => '62', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-28 18:01:44', 'updated_at' => '2021-07-28 18:01:44', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '47', 'target_id' => '1', 'reference_id' => '63', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-07-28 18:04:03', 'updated_at' => '2021-07-28 18:04:03', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '38', 'target_id' => '54', 'reference_id' => '65', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-08-06 20:29:41', 'updated_at' => '2021-08-06 20:29:41', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '54', 'target_id' => '38', 'reference_id' => '64', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-08-06 21:09:16', 'updated_at' => '2021-08-06 21:09:16', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '55', 'target_id' => '53', 'reference_id' => '67', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-08-07 16:54:02', 'updated_at' => '2021-08-07 16:54:02', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '53', 'target_id' => '55', 'reference_id' => '66', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-08-07 16:54:10', 'updated_at' => '2021-08-07 16:54:10', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '43', 'target_id' => '38', 'reference_id' => '51', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-08-07 20:50:10', 'updated_at' => '2021-08-07 20:50:10', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '55', 'target_id' => '43', 'reference_id' => '68', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-08-07 20:51:24', 'updated_at' => '2021-08-07 20:51:24', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '43', 'target_id' => '55', 'reference_id' => '69', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-08-07 20:52:33', 'updated_at' => '2021-08-07 20:52:33', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '43', 'target_id' => '53', 'reference_id' => '70', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-08-09 18:15:59', 'updated_at' => '2021-08-09 18:15:59', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '1', 'actor_id' => '53', 'target_id' => '58', 'reference_id' => '81', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-08-17 18:45:47', 'updated_at' => '2021-08-17 18:45:47', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '53', 'target_id' => '58', 'reference_id' => '80', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-08-17 18:46:13', 'updated_at' => '2021-08-17 18:46:13', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '1', 'actor_id' => '43', 'target_id' => '53', 'reference_id' => '82', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-09-01 12:34:29', 'updated_at' => '2021-09-01 12:34:29', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '57', 'target_id' => '5', 'reference_id' => '84', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-09-08 15:41:22', 'updated_at' => '2021-09-08 15:41:22', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '1', 'actor_id' => '61', 'target_id' => '60', 'reference_id' => '85', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-10-13 06:20:52', 'updated_at' => '2021-10-13 06:20:52', 'custom_data' => NULL, 'status_code' => '0'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '63', 'reference_id' => '86', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-10-14 14:43:18', 'updated_at' => '2021-10-14 14:43:18', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '63', 'target_id' => '5', 'reference_id' => '87', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-10-14 14:43:38', 'updated_at' => '2021-10-14 14:43:38', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '57', 'reference_id' => '83', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-10-14 14:43:43', 'updated_at' => '2021-10-14 14:43:43', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '24', 'reference_id' => '22', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-10-15 12:37:07', 'updated_at' => '2021-10-15 12:37:07', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '7', 'target_id' => '26', 'reference_id' => '26', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-10-29 12:35:18', 'updated_at' => '2021-10-29 12:35:18', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '62', 'target_id' => '1', 'reference_id' => '94', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-11-04 13:21:12', 'updated_at' => '2021-11-04 13:21:12', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '1', 'target_id' => '62', 'reference_id' => '95', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-11-04 13:23:23', 'updated_at' => '2021-11-04 13:23:23', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '8', 'actor_id' => '5', 'target_id' => '62', 'reference_id' => '93', 'reference_module' => 'request_accepted', 'type' => 'push', 'title' => 'Request Accepted', 'description' => 'Request Accepted', 'is_notify' => '0', 'is_read' => '1', 'is_viewed' => '0', 'created_at' => '2021-11-04 14:03:29', 'updated_at' => '2021-11-04 14:03:29', 'custom_data' => NULL, 'status_code' => '1'],
            ['notification_identifier_id' => '9', 'actor_id' => '24', 'target_id' => '5', 'reference_id' => '21', 'reference_module' => 'request_rejected', 'type' => 'push', 'title' => 'Request Rejected', 'description' => 'Request Rejected', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-11-08 10:29:04', 'updated_at' => '2021-11-08 10:29:04', 'custom_data' => NULL, 'status_code' => '2'],
            ['notification_identifier_id' => '1', 'actor_id' => '53', 'target_id' => '6', 'reference_id' => '99', 'reference_module' => 'add_friend', 'type' => 'push', 'title' => 'Add Friend', 'description' => 'New Friend Notification', 'is_notify' => '0', 'is_read' => '0', 'is_viewed' => '0', 'created_at' => '2021-11-12 17:03:37', 'updated_at' => '2021-11-12 17:03:37', 'custom_data' => NULL, 'status_code' => '0']
        ]);
    }
}
